#!/bin/sh

COMMAND="firebox"

profile_dir="$("$COMMAND" config print_profile_dir)"
sep="$("$COMMAND" config print_separator)"
sep_esc="$("$COMMAND" config print_separator --escaped)"

if [ -d "$profile_dir" ]; then
	options="service\nworkspace\nexplorer"
else
	options="init"
fi

dmenu_cmd() {
	dmenu -i "$@"
}

print_log() {
	echo "$1" >&2
}

select_stuff() {
	action="$1"
	shift

	prompt="Select $action(s):"

	if [ "$action" = "custom" ]; then
		options="$1"
		prompt="Select services:"
		shift
	else
		if [ "$action" = "workspace" ]; then
			options="$("$COMMAND" workspace list --all --raw | sed "s/$sep.*//g")"
		else
			options="$("$COMMAND" service list --raw | sed "s/$sep.*//g")"
		fi
	fi

	if [ "$1" = "--once" ]; then
		once="--once"
		shift
	else
		options="== Confirm ==\n$options"
	fi

	selection=""

	if [ -n "$options" ]; then
		while true; do
			current_selection="$(echo "$options" | dmenu_cmd -p "$prompt" "$@")"

			if [ -z "$current_selection" ]; then
				selection=""
				break
			fi

			if [ "$current_selection" != "== Confirm ==" ]; then
				selection_name=$(echo "$current_selection" | sed 's/^* //')
				if echo "$selection" | grep -q " '$selection_name'\s*"; then
					options=$(echo "$options" | sed "/* $selection_name/{s/^* //}")
					selection=$(echo "$selection" | sed "s/'$selection_name'//")
				else
					options=$(echo "$options" | sed "/$current_selection/{s/^/* /}")
					selection="$selection '$current_selection'"
				fi
			else
				break
			fi

			[ "$once" = "--once" ] && break
		done
	fi

	echo "$selection" | sed 's/^\s*//'

}

launch_stuff() {
	action="$1"
	shift
	selection=$(select_stuff "$action" "$@")

	[ -n "$selection" ] && echo "$selection" | xargs "$COMMAND" "$action" launch
}

explorer() {
	"$TERMINAL" sh -c "$COMMAND explorer && printf '\n\nPress any key to close' && read -r confirm"
}

service() {
	options="list\nlaunch"
	option=$(echo "$options" | dmenu_cmd -p "Firebox Services:" "$@")

	case "$option" in
	list)
		"$TERMINAL" sh -c "echo 'Available services:\n' && $COMMAND service list && printf '\n\nPress any key to close' && read -r confirm"
		;;
	launch)
		launch_stuff service "$@"
		;;
	*)
		echo "Invalid option" &&
			exit 1
		;;
	esac
}

add_to_workspace() {
	[ -n "$1" ] && services=$(select_stuff service)

	{ [ -n "$1" ] && [ -n "$services" ]; } &&
		echo "$1" "$services" | xargs "$COMMAND" workspace add
}

workspace() {
  workspaces=$("$COMMAND" workspace list --all)

  if [ -z "$workspaces" ]; then
    options="create"
  else
    options="create\nlist\nlaunch\nadd\nremove\ndelete"
  fi

	option=$(echo "$options" | dmenu_cmd -p "Firebox Services:" "$@")

	case "$option" in
	create)
		workspace_name=$(dmenu_cmd -p "Enter service name:" <&-)
		echo "$workspace_name"
		"$COMMAND" workspace create "$workspace_name" &&
			add_to_workspace "$workspace_name"
		;;
	list)
		workspace_name=$(select_stuff custom "== ALL ==\n$("$COMMAND" workspace list --all --raw | sed "s/$sep.*//")" --once)
		[ "$workspace_name" = "== ALL ==" ] && workspace_name="--all"
		"$TERMINAL" sh -c "echo 'Available services:\n' && $COMMAND workspace list $workspace_name && printf '\n\nPress any key to close' && read -r confirm"
		;;
	launch)
		launch_stuff workspace --once
		;;
	add)
		print_log "add"
		if [ "$1" = "--workspace" ]; then
			print_log "waka waka"
			workspace_name="$2" &&
				shift && shift
		else
			workspace_name=$(select_stuff workspace --once)
		fi

		add_to_workspace "$workspace_name"
		;;
	remove)
		workspace_name=$(select_stuff workspace --once)
		if [ -n "$workspace_name" ]; then
			available_services=$(echo "$workspace_name" | xargs -I "{}" "$COMMAND" workspace list "{}" --raw | grep -iEo "$sep_esc.*\$" | sed "s/$sep//;s/$sep/\n/g;")
			if [ -n "$available_services" ]; then
				services=$(select_stuff custom "$available_services")
			else
				echo "Workspace Empty"
			fi
			[ -n "$services" ] &&
				echo "$workspace_name" "$services" | xargs "$COMMAND" workspace remove
		fi
		;;
	delete)
		workspace_name=$(select_stuff workspace --once)
		[ -n "$workspace_name" ] && "$TERMINAL" sh -c "$COMMAND workspace delete $workspace_name && printf '\n\nPress any key to close' && read -r confirm"
		;;
	*)
		echo "Invalid option" &&
			exit 1
		;;
	esac
}

option=$(echo "$options" | dmenu_cmd -p "Firebox" "$@")

init() {
	"$TERMINAL" sh -c "$COMMAND init && printf '\n\nPress any key to close' && read -r confirm"
}

case "$option" in
init | explorer | service | workspace)
	"$option" "$@"
	;;
*)
	echo "Invalid option" &&
		exit 1
	;;
esac
